language: rust
rust:
    - stable
    - beta
    - nightly
matrix:
    allow_failures:
      - rust: nightly
os:
  - linux
  - osx
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
